name: Blackpixel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.89981
title: Blackpixel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2a2a'
    - '#f9f9f9'
    - '#757581'
    - '#a2b4b4'
    - '#9fe3f4'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.846510116243735
purpose: []
