name: Blackpixel
favicon: null
layout_spectrum: 0.6235954049043357
typography_spectrum: 0.602757039712742
title: Blackpixel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4251996870152652
  lightness: 0.5779609254095703
  saturation: 0.28112177131697536
  rhythmicContrast: 0.846510116243735
purpose: []
